import type { LessonElement } from '@shared/elements.ts';

/**
 * One realistic sample instance per implemented element, for the dev
 * gallery (`#/dev/elements`). Grows by one entry per renderer task.
 */
export const GALLERY_SAMPLES: LessonElement[] = [
  { type: 'array', rows: 3, cols: 5, animate: 'rotate' },
  {
    type: 'text',
    value: 'Every sentence needs a noun — a word that names a person, place, thing, or idea.',
    emphasis: 'term',
    term: 'Noun',
    definition: 'A word that names a person, place, thing, or idea.',
  },
  {
    type: 'image',
    src: '',
    alt: 'A diagram of the water cycle, showing water moving between clouds, rain, and the ocean',
    caption: 'The water cycle',
    annotate: ['Evaporation', 'Condensation', 'Precipitation'],
  },
  {
    type: 'video',
    searchTerm: 'how plants make food — photosynthesis for kids',
    watchTask: 'Watch how plants turn sunlight into food.',
    afterCheck: { question: 'What gas do plants release during photosynthesis?', expectedAnswer: 'oxygen' },
  },
  {
    type: 'scene',
    items: [
      { emoji: '🍎', count: 4, label: 'apples' },
      { emoji: '🍌', count: 3, label: 'bananas' },
    ],
    layout: 'row',
    caption: 'How many pieces of fruit in total?',
  },
  {
    type: 'audio',
    src: '',
    label: 'A dog barking',
    listenTask: 'Listen closely — what do you hear?',
  },
  {
    type: 'numberLine',
    min: 0,
    max: 12,
    step: 3,
    jumps: [0, 3, 6, 9],
    target: 9,
  },
  {
    type: 'baseTen',
    value: 47,
    mode: 'blocks',
    target: 47,
  },
  {
    type: 'fraction',
    whole: ['circle'],
    num: 3,
    den: 4,
  },
  {
    type: 'barModel',
    whole: 12,
    parts: [7, '?'],
    label: 'There are 12 sweets. 7 are red, the rest are blue.',
  },
  {
    type: 'numberBond',
    whole: 10,
    parts: [6, '?'],
  },
  { type: 'shape', mode: '2d', spec: 'hexagon' },
  { type: 'shape', mode: '3d', spec: 'cylinder' },
  { type: 'shape', mode: 'angle', spec: 'obtuse 130' },
  { type: 'shape', mode: 'symmetry', spec: 'rectangle' },
  { type: 'shape', mode: 'net', spec: 'cube' },
  {
    type: 'grid',
    rows: 5,
    cols: 5,
    mode: 'coord',
    cells: [
      { x: 1, y: 1, label: 'A' },
      { x: 3, y: 4, label: 'B' },
    ],
    target: { x: 2, y: 3 },
  },
  {
    type: 'grid',
    rows: 4,
    cols: 4,
    mode: 'beebot',
    cells: [
      { x: 0, y: 0 },
      { x: 0, y: 2 },
      { x: 2, y: 2 },
    ],
    target: { x: 3, y: 2 },
  },
  {
    type: 'grid',
    rows: 4,
    cols: 4,
    mode: 'pixel',
    cells: [
      { x: 1, y: 1, fill: 'var(--el-pink)' },
      { x: 2, y: 1, fill: 'var(--el-pink)' },
      { x: 1, y: 2, fill: 'var(--el-purple)' },
      { x: 2, y: 2, fill: 'var(--el-purple)' },
    ],
    target: { x: 0, y: 0 },
  },
  {
    type: 'dataChart',
    kind: 'bar',
    data: [
      { label: 'Cat', value: 6 },
      { label: 'Dog', value: 9 },
      { label: 'Fish', value: 4 },
    ],
    unit: 'votes',
  },
  {
    type: 'dataChart',
    kind: 'pie',
    data: [
      { label: 'Red', value: 3 },
      { label: 'Blue', value: 5 },
      { label: 'Green', value: 2 },
    ],
  },
  {
    type: 'dataChart',
    kind: 'pictogram',
    data: [
      { label: 'Apples', value: 4 },
      { label: 'Bananas', value: 7 },
    ],
    unit: 'pieces',
  },
  {
    type: 'dataChart',
    kind: 'table',
    data: [
      { label: 'Mon', value: 12 },
      { label: 'Tue', value: 18 },
      { label: 'Wed', value: 9 },
    ],
    unit: 'steps (00s)',
  },
  {
    type: 'dataChart',
    kind: 'line',
    data: [
      { label: 'Jan', value: 4 },
      { label: 'Feb', value: 7 },
      { label: 'Mar', value: 6 },
      { label: 'Apr', value: 10 },
    ],
    unit: '°C',
  },
  { type: 'measure', mode: 'clock', value: 150, target: 195 },
  { type: 'measure', mode: 'money', value: 87, target: 132 },
  { type: 'measure', mode: 'ruler', value: 12, target: 18, unit: 'cm' },
  { type: 'measure', mode: 'scale', value: 4, target: 7, unit: 'kg' },
  { type: 'measure', mode: 'jug', value: 250, target: 600, unit: 'ml' },
  { type: 'measure', mode: 'thermo', value: 18, target: 25, unit: '°C' },
  {
    type: 'wordBuild',
    word: 'ship',
    split: 'phoneme',
  },
  {
    type: 'textMark',
    passage: 'The quick fox jumped over the lazy dog.',
    mode: 'highlight',
    marks: ['fox', 'dog'],
  },
  {
    type: 'sentence',
    words: ['The', 'cat', 'sat', 'on', 'the', 'mat'],
    label: 'order',
  },
  {
    type: 'diagram',
    mode: 'label',
    nodes: [
      { id: 'root', label: 'Root', x: 20, y: 85 },
      { id: 'stem', label: 'Stem', x: 50, y: 50 },
      { id: 'leaf', label: 'Leaf', x: 78, y: 30 },
      { id: 'flower', label: 'Flower', x: 50, y: 10 },
    ],
  },
  {
    type: 'diagram',
    mode: 'cycle',
    nodes: [
      { id: 'egg', label: 'Egg' },
      { id: 'larva', label: 'Larva' },
      { id: 'pupa', label: 'Pupa' },
      { id: 'adult', label: 'Adult' },
    ],
  },
  {
    type: 'diagram',
    mode: 'flow',
    nodes: [
      { id: 'input', label: 'Get input' },
      { id: 'check', label: 'Is it even?' },
      { id: 'yes', label: 'Print "even"' },
      { id: 'no', label: 'Print "odd"' },
    ],
    edges: [
      { from: 'input', to: 'check' },
      { from: 'check', to: 'yes', label: 'yes' },
      { from: 'check', to: 'no', label: 'no' },
    ],
  },
  {
    type: 'diagram',
    mode: 'web',
    nodes: [
      { id: 'grass', label: 'Grass' },
      { id: 'rabbit', label: 'Rabbit' },
      { id: 'fox', label: 'Fox' },
      { id: 'hawk', label: 'Hawk' },
    ],
    edges: [
      { from: 'grass', to: 'rabbit' },
      { from: 'rabbit', to: 'fox' },
      { from: 'rabbit', to: 'hawk' },
      { from: 'grass', to: 'hawk' },
    ],
  },
  {
    type: 'diagram',
    mode: 'mindmap',
    nodes: [
      { id: 'space', label: 'Space' },
      { id: 'planets', label: 'Planets' },
      { id: 'stars', label: 'Stars' },
      { id: 'earth', label: 'Earth' },
      { id: 'mars', label: 'Mars' },
      { id: 'sun', label: 'Sun' },
    ],
    edges: [
      { from: 'space', to: 'planets' },
      { from: 'space', to: 'stars' },
      { from: 'planets', to: 'earth' },
      { from: 'planets', to: 'mars' },
      { from: 'stars', to: 'sun' },
    ],
  },
  {
    type: 'map',
    scope: 'world',
    regions: ['Africa', 'Asia', 'Europe'],
    pins: [
      { x: 48, y: 55, label: 'Cairo' },
      { x: 78, y: 42, label: 'Tokyo' },
      { x: 52, y: 28, label: 'London' },
    ],
    routes: [{ from: 'London', to: 'Cairo' }],
  },
  {
    type: 'timeline',
    events: [
      { when: '1800s', label: 'Steam trains invented' },
      { when: '1903', label: 'First aeroplane flight' },
      { when: '1969', label: 'Moon landing' },
      { when: '2020s', label: 'Reusable rockets' },
    ],
    scale: 'Not to scale — key milestones only',
  },
  {
    type: 'sort',
    mode: 'bucket',
    groups: ['Mammals', 'Birds'],
    items: [
      { text: 'Dog', group: 'Mammals' },
      { text: 'Eagle', group: 'Birds' },
      { text: 'Whale', group: 'Mammals' },
      { text: 'Penguin', group: 'Birds' },
    ],
  },
  {
    type: 'sort',
    mode: 'venn',
    groups: ['Herbivores', 'Carnivores'],
    items: [
      { text: 'Rabbit', group: 'Herbivores' },
      { text: 'Lion', group: 'Carnivores' },
      { text: 'Deer', group: 'Herbivores' },
      { text: 'Wolf', group: 'Carnivores' },
    ],
  },
  {
    type: 'sort',
    mode: 'rank',
    groups: ['Fastest', 'Middle', 'Slowest'],
    items: [
      { text: 'Cheetah', group: 'Fastest' },
      { text: 'Horse', group: 'Middle' },
      { text: 'Tortoise', group: 'Slowest' },
    ],
  },
  {
    type: 'music',
    mode: 'staff',
    spec: 'do re mi fa sol',
  },
  {
    type: 'music',
    mode: 'rhythm',
    spec: 'ta ta ti-ti ta',
  },
  {
    type: 'music',
    mode: 'keyboard',
    spec: 'C E G',
  },
  {
    type: 'draw',
    prompt: 'Draw your favourite animal!',
    guides: 'circle',
  },
  {
    type: 'steps',
    reveal: 'one-by-one',
    slides: [
      { title: 'Step 1', body: 'Start with 24 ÷ 4.' },
      { title: 'Step 2', body: 'How many groups of 4 fit into 24? Count up by 4s: 4, 8, 12, 16, 20, 24.' },
      { title: 'Step 3', body: 'That took 6 jumps of 4, so 24 ÷ 4 = 6.' },
    ],
  },
  {
    type: 'choice',
    prompt: 'Which planet is closest to the Sun?',
    options: ['Venus', 'Mercury', 'Earth', 'Mars'],
    correct: [1],
    explain: 'Mercury orbits closest to the Sun, so it has the shortest year.',
  },
  {
    type: 'choice',
    prompt: 'Which of these are mammals? Pick all that apply.',
    options: ['Dolphin', 'Shark', 'Bat', 'Eagle'],
    correct: [0, 2],
    explain: 'Dolphins and bats feed their young milk — sharks and eagles do not.',
  },
  {
    type: 'enter',
    prompt: 'What is 7 × 8?',
    answer: '56',
    kind: 'number',
  },
  {
    type: 'enter',
    prompt: 'What do we call a word that names a person, place, thing, or idea?',
    answer: 'noun',
    kind: 'text',
  },
  {
    type: 'speak',
    prompt: 'Say the past tense of "run".',
    target: 'ran',
  },
];
